services:
  sqlserver:
    build: .
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - C:\Armazenamento\Volumes\Rabbit:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest